import {
  createBaseThemeOptions,
  createUnifiedTheme,
  palettes,
} from '@backstage/theme';

const palette = {
  primary: '#78DCE8',
  primaryT: '#78DCE890',
  accent: '#74a0f1',
  link: '#34d3fb',
  accentT: '#74a0f190',
  accent2: '#34d3fb',
  accent2T: '#34d3fb90',
  bg: '#222436',
  fg: '#c8d3f5',
  text: '#a9b8e8',
  selectBg: '#444a73',
  selBg: '#444a73',
  selectFg: '#FFFFFF',
  selFg: '#FFFFFF',
  button: '#444a73',
  secondBg: '#2f334d',
  lbg: '#2f334d',
  second: '#2f334d',
  disabled: '#828bb8',
  contrast: '#191a2a',
  dbg: '#191a2a',
  active: '#2f334d',
  border: '#222436',
  hl: '#444a73',
  tree: '#444a7370',
  notif: '#191a2a',
  excluded: '#2f334d',
  excl: '#2f334d',
  yellow: '#ffdb8e',
  attribute: '#ffbd76',
  green: '#7af8ca',
  string: '#7af8ca',
  cyan: '#34d3fb',
  operator: '#baacff',
  blue: '#70b0ff',
  function: '#70b0ff',
  purple: '#baacff',
  keyword: '#baacff',
  class: '#ffbd76',
  red: '#f3c1ff',
  tag: '#ff757f',
  red2: '#ff5370',
  error: '#ff5370',
  orange: '#ff9668',
  number: '#ff9668',
  orange2: '#ff9668',
  parameter: '#f3c1ff',
  gray: '#7e8eda',
  comment: '#7e8eda',
  silver: '#c8d3f5',
  variable: '#c8d3f5',
  black: '#c8d3f5',
};

export const moonlight = createUnifiedTheme({
  ...createBaseThemeOptions({
    palette: {
      ...palettes.dark,
      background: {
        default: palette.bg,
        paper: palette.second,
      },
      primary: {
        main: palette.accent,
      },
      banner: {
        closeButtonColor: palette.fg,
        info: palette.notif,
        error: palette.error,
        text: palette.fg,
        link: palette.link,
        warning: palette.yellow,
      },
      border: palette.hl,
      textContrast: palette.selFg,
      textVerySubtle: palette.disabled,
      textSubtle: palette.text,
      highlight: palette.hl,
      errorBackground: palette.error,
      warningBackground: palette.yellow,
      infoBackground: palette.notif,
      errorText: palette.fg,
      infoText: palette.fg,
      warningText: palette.fg,
      linkHover: palette.accent,
      link: palette.link,
      gold: palette.accent2,
      navigation: {
        background: palette.contrast,
        indicator: palette.accent,
        color: palette.fg,
        selectedColor: palette.accent,
        navItem: {
          hoverBackground: palette.tree,
        },
        submenu: {
          background: palette.second,
        },
      },
      pinSidebarButton: {
        icon: palette.fg,
        background: palette.button,
      },
      tabbar: {
        indicator: palette.accent,
      },
    },
  }),
  fontFamily: 'Roboto',
  defaultPageTheme: 'home',
});
